/**
 * CONSTELLATION — Shared Constants
 *
 * Canonical entity types, relationship types, and other constants
 * shared between frontend and backend.
 */

export const ENTITY_TYPES = Object.freeze({
  PERSON: 'person',
  CRIMINAL: 'criminal',
  SUSPECT: 'suspect',
  ORGANIZATION: 'organization',
  PHONE: 'phone',
  VEHICLE: 'vehicle',
  LOCATION: 'location',
  CRIME: 'crime',
  FIR: 'fir',
  CASE: 'case',
  EVENT: 'event',
  COMMUNICATION: 'communication',
  TRANSACTION: 'transaction',
  EVIDENCE: 'evidence',
  DOCUMENT: 'document',
  DEVICE: 'device',
  DIGITAL_IDENTITY: 'digital_identity',
  SOCIAL_ACCOUNT: 'social_account',
  ADDRESS: 'address',
  COURT_RECORD: 'court_record',
  IMAGE_EVIDENCE: 'image_evidence',
  TIMELINE_EVENT: 'timeline_event',
});

export const RELATIONSHIP_TYPES = Object.freeze({
  KNOWS: 'KNOWS',
  COMMUNICATED_WITH: 'COMMUNICATED_WITH',
  CALLED: 'CALLED',
  MESSAGED: 'MESSAGED',
  ASSOCIATED_WITH: 'ASSOCIATED_WITH',
  MEMBER_OF: 'MEMBER_OF',
  OWNS: 'OWNS',
  USED: 'USED',
  LOCATED_AT: 'LOCATED_AT',
  VISITED: 'VISITED',
  INVOLVED_IN: 'INVOLVED_IN',
  LINKED_TO_CASE: 'LINKED_TO_CASE',
  MENTIONED_IN: 'MENTIONED_IN',
  APPEARS_IN: 'APPEARS_IN',
  CONNECTED_TO: 'CONNECTED_TO',
  TRANSFERRED_TO: 'TRANSFERRED_TO',
  TRANSACTED_WITH: 'TRANSACTED_WITH',
  RELATED_TO: 'RELATED_TO',
  EVIDENCE_FOR: 'EVIDENCE_FOR',
  OCCURRED_AT: 'OCCURRED_AT',
  SAME_SOURCE_IMAGE: 'SAME_SOURCE_IMAGE',
  IMAGE_OCCURRENCE: 'IMAGE_OCCURRENCE',
  POTENTIAL_RELATIONSHIP: 'POTENTIAL_RELATIONSHIP',
});

/** Human-readable labels for entity types */
export const ENTITY_TYPE_LABELS = Object.freeze({
  [ENTITY_TYPES.PERSON]: 'Person',
  [ENTITY_TYPES.CRIMINAL]: 'Criminal',
  [ENTITY_TYPES.SUSPECT]: 'Suspect',
  [ENTITY_TYPES.ORGANIZATION]: 'Organization',
  [ENTITY_TYPES.PHONE]: 'Phone',
  [ENTITY_TYPES.VEHICLE]: 'Vehicle',
  [ENTITY_TYPES.LOCATION]: 'Location',
  [ENTITY_TYPES.CRIME]: 'Crime',
  [ENTITY_TYPES.FIR]: 'FIR',
  [ENTITY_TYPES.CASE]: 'Case',
  [ENTITY_TYPES.EVENT]: 'Event',
  [ENTITY_TYPES.COMMUNICATION]: 'Communication',
  [ENTITY_TYPES.TRANSACTION]: 'Transaction',
  [ENTITY_TYPES.EVIDENCE]: 'Evidence',
  [ENTITY_TYPES.DOCUMENT]: 'Document',
  [ENTITY_TYPES.DEVICE]: 'Device',
  [ENTITY_TYPES.DIGITAL_IDENTITY]: 'Digital Identity',
  [ENTITY_TYPES.SOCIAL_ACCOUNT]: 'Social Account',
  [ENTITY_TYPES.ADDRESS]: 'Address',
  [ENTITY_TYPES.COURT_RECORD]: 'Court Record',
  [ENTITY_TYPES.IMAGE_EVIDENCE]: 'Image Evidence',
  [ENTITY_TYPES.TIMELINE_EVENT]: 'Timeline Event',
});

/** Human-readable labels for relationship types */
export const RELATIONSHIP_TYPE_LABELS = Object.freeze({
  [RELATIONSHIP_TYPES.KNOWS]: 'Knows',
  [RELATIONSHIP_TYPES.COMMUNICATED_WITH]: 'Communicated With',
  [RELATIONSHIP_TYPES.CALLED]: 'Called',
  [RELATIONSHIP_TYPES.MESSAGED]: 'Messaged',
  [RELATIONSHIP_TYPES.ASSOCIATED_WITH]: 'Associated With',
  [RELATIONSHIP_TYPES.MEMBER_OF]: 'Member Of',
  [RELATIONSHIP_TYPES.OWNS]: 'Owns',
  [RELATIONSHIP_TYPES.USED]: 'Used',
  [RELATIONSHIP_TYPES.LOCATED_AT]: 'Located At',
  [RELATIONSHIP_TYPES.VISITED]: 'Visited',
  [RELATIONSHIP_TYPES.INVOLVED_IN]: 'Involved In',
  [RELATIONSHIP_TYPES.LINKED_TO_CASE]: 'Linked To Case',
  [RELATIONSHIP_TYPES.MENTIONED_IN]: 'Mentioned In',
  [RELATIONSHIP_TYPES.APPEARS_IN]: 'Appears In',
  [RELATIONSHIP_TYPES.CONNECTED_TO]: 'Connected To',
  [RELATIONSHIP_TYPES.TRANSFERRED_TO]: 'Transferred To',
  [RELATIONSHIP_TYPES.TRANSACTED_WITH]: 'Transacted With',
  [RELATIONSHIP_TYPES.RELATED_TO]: 'Related To',
  [RELATIONSHIP_TYPES.EVIDENCE_FOR]: 'Evidence For',
  [RELATIONSHIP_TYPES.OCCURRED_AT]: 'Occurred At',
  [RELATIONSHIP_TYPES.SAME_SOURCE_IMAGE]: 'Same Source Image',
  [RELATIONSHIP_TYPES.IMAGE_OCCURRENCE]: 'Image Occurrence',
  [RELATIONSHIP_TYPES.POTENTIAL_RELATIONSHIP]: 'Potential Relationship',
});

/** Entity type categories for grouping in UI */
export const ENTITY_CATEGORIES = Object.freeze({
  PEOPLE: [ENTITY_TYPES.PERSON, ENTITY_TYPES.CRIMINAL, ENTITY_TYPES.SUSPECT],
  ORGANIZATIONS: [ENTITY_TYPES.ORGANIZATION],
  COMMUNICATION: [ENTITY_TYPES.PHONE, ENTITY_TYPES.COMMUNICATION, ENTITY_TYPES.DIGITAL_IDENTITY, ENTITY_TYPES.SOCIAL_ACCOUNT],
  PHYSICAL: [ENTITY_TYPES.VEHICLE, ENTITY_TYPES.DEVICE, ENTITY_TYPES.ADDRESS],
  LOCATIONS: [ENTITY_TYPES.LOCATION],
  LEGAL: [ENTITY_TYPES.CRIME, ENTITY_TYPES.FIR, ENTITY_TYPES.CASE, ENTITY_TYPES.COURT_RECORD],
  EVENTS: [ENTITY_TYPES.EVENT, ENTITY_TYPES.TIMELINE_EVENT],
  FINANCIAL: [ENTITY_TYPES.TRANSACTION],
  EVIDENCE: [ENTITY_TYPES.EVIDENCE, ENTITY_TYPES.DOCUMENT, ENTITY_TYPES.IMAGE_EVIDENCE],
});

/** Standard API response status codes */
export const API_ERRORS = Object.freeze({
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  ENTITY_NOT_FOUND: 'ENTITY_NOT_FOUND',
  CASE_NOT_FOUND: 'CASE_NOT_FOUND',
  RELATIONSHIP_NOT_FOUND: 'RELATIONSHIP_NOT_FOUND',
});
